research_task:
  description: >
    Research the topic {topic} and gather latest information about it.
    Prepare insights and key points that will be used to create a outline for a book 
    by the outline writer Agent.
  expected_output: >
    A list of insights and key points about the topic {topic}.
  agent: research_agent

write_outline:
  description: >
    Write a outline for a book about {topic}.
    Ensure the outline is engaging and adheres to what a good outline should be.
  expected_output: >
    A beautifully crafted outline for a book about {topic} in the following format
    - total chapters
    - list of titles
  agent: outline_writer